export default function translate(prop: string): string {
  const props = {
    mb: 'marginBottom',
    mt: 'marginTop',
    ml: 'marginLeft',
    mr: 'marginRight',
    pb: 'paddingBottom',
    pt: 'paddingTop',
    pl: 'paddingLeft',
    pr: 'paddingRight',
    bg: 'backgroundColor',
    bgColor: 'backgroundColor',
    elevation: 'boxShadow',
    c: 'color',
    fs: 'fontSize',
    lh: 'lineHeight',
    ta: 'textAlign',
    tt: 'textTransform',
    d: 'display',
    of: 'overflow',
    ox: 'overflowX',
    oy: 'overflowY',
    p: 'padding',
    m: 'margin',
    b: 'border',
    fw: 'fontWeight',
    w: 'width',
    h: 'height',
    pv: 'paddingVertical',
    ph: 'paddingHorizontal',
    mv: 'marginVertical',
    mh: 'marginHorizontal',
    bRadius: 'borderRadius',
  };

  return props[prop] || prop;
}
